config/routes.rb
NewsSucks::Application.routes.draw do
  devise_for :users

  root :to => "articles#index"

  resources :articles, only:[:index, :show, :create, :update] do
    member do
      get :review
    end
    scope module: 'article' do
      resources :lines
    end
    resources :links
  end
  scope module: 'article' do
    resources :reviews
  end
  resources :suggestions, only:[:new, :create]

  resources :users, only:[:show]

  resources :identities, only:[:index, :create, :destroy]
  match '/auth/:provider/callback', to: 'identities#create'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :reporter_name, :content, :published_at, :url, :company_name
  attr_accessor :reproduced

  has_many :'lines', class_name:'Article::Line'
  has_many :line_reviews, :through => :lines, :source => :reviews
  has_many :reviews, class_name:'Article::Review', :as => :reviewable
  has_many :links

  def reproduced?
    if reproduced
      errors.add(:base, "新聞轉載")
    end
  end

  def self.find_existing(domain, url_id)
    Article.where(web_domain:domain,url_id:url_id).first
  end

  def content_lines
    if ! @content_lines
      @content_lines = [title]
      @content_lines.concat SentenceSplitter.split(content)
    end
    @content_lines
  end

  before_create :build_lines
  def build_lines
    content_lines.each_with_index do |line, index|
      lines.build(text:line, line_number:index+1)
    end
  end
end

# == Schema Information
#
# Table name: articles
#
#  id                 :integer          not null, primary key
#  title              :string(255)      not null
#  reporter_name      :string(255)
#  content            :text             default(""), not null
#  published_at       :datetime
#  url                :string(255)      not null
#  company_name       :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  web_domain         :string(255)
#  url_id             :string(255)
#  line_reviews_count :integer          default(0), not null
#

app/models/article/line.rb
class Article::Line < ActiveRecord::Base
  belongs_to :article
  has_many :reviews, :as => :reviewable
  attr_accessible :line_number, :text

  def self.model_name
    ActiveModel::Name.new(self, Article)
  end
end

# == Schema Information
#
# Table name: article_lines
#
#  id            :integer          not null, primary key
#  article_id    :integer
#  line_number   :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  text          :text
#  reviews_count :integer          default(0), not null
#

app/models/article/review.rb
class Article::Review < ActiveRecord::Base
  belongs_to :reviewable, polymorphic:true, counter_cache: true
  belongs_to :user
  attr_accessible :reviewable_type, :reviewable_id, :text, :tag_list, :involved_personally, :user_id

  after_commit :update_article_counter

  acts_as_taggable

  auto_html_for :text do
    link :target => "_blank", :rel => "nofollow"
  end

  def self.model_name
    ActiveModel::Name.new(self, Article)
  end

  def update_article_counter
    if reviewable_type == 'Article::Line'
      article = reviewable.article
      count = article.line_reviews.count
      article.update_column(:line_reviews_count, count)
    end
  end
end

# == Schema Information
#
# Table name: article_reviews
#
#  id                  :integer          not null, primary key
#  reviewable_id       :integer
#  reviewable_type     :string(64)
#  text                :text
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :integer          not null
#  involved_personally :boolean          default(FALSE), not null
#

app/controllers/article/reviews_controller.rb
class Article::ReviewsController < ApplicationController
  load_and_authorize_resource class:'Article::Review'

  def new
    if params[:line_id]
      line = Article::Line.find(params[:line_id])
      @review.reviewable = line
    end
  end

  def edit
  end

  def create
    @review.user = current_user
    if @review.save
      redirect_to review_article_path(@review.reviewable.article)
    else
      logger.debug @review.errors
      #flash[:error] = @review.tags.map{|t| t.errors.full_messages}
      render :new
    end
  end

  def update
  end

  def destroy
    if @review.destroy
    else
      flash[:error] = '刪除失敗'
    end
    redirect_to :back
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource

  def index
    @articles = @articles.where{line_reviews_count != 0}.order('id DESC').page(params[:page]).per(15)
  end

  def create
    url = params[:url]
    if !url.ascii_only?
      url = URI.encode(url)
    end

    parser = TaiwaneseNewsParser.new(url)

    if parser.nil?
      raise NewsSucks::ParserNotExistError
    elsif ( parser.article[:web_domain].blank? ||  parser.article[:url_id].blank? )
      raise # debugging
    end

    # Use article if already fetched before
    if @article = Article.find_existing(parser.article[:web_domain], parser.article[:url_id])
      redirect_to review_article_path(@article) and return
    end

    hash = parser.parse

    @article = Article.new(hash.except(:web_domain, :url_id, :reproduced))
    @article.web_domain = hash[:web_domain]
    @article.url_id = hash[:url_id]

    if @article.save
      redirect_to review_article_path(@article)
    else
      puts @article.errors[:base].inspect
      puts @article.valid?
      if @article.errors[:base].find{|e| e.include?('新聞轉載')}
        render :reproduced and return
      end
      redirect_to @article
    end
  rescue Exception => e
    logger.parser.error(params[:url])
    logger.parser.error(e.inspect)
    Suggestion.create(content:"解析器問題：#{params[:url]}。#{e.inspect}")

    if Rails.env.development?
      raise
    elsif e.is_a? NewsSucks::ParserNotExistError
      flash[:error] = '抱歉，目前還沒辦法抓取這個網站的內容。中國時報只能抓新版網站，東森新聞只能抓 Ettoday。'
      redirect_to action: :index
    else
      flash[:error] = '抱歉，這篇新聞抓取時發生問題，已經通知站長，預計一週內會修復。'
      redirect_to action: :index
    end
  end

  def show
  end

  # GET
  def review
    ActiveRecord::Associations::Preloader.new(@article,:lines => :reviews).run()
  end

  def update
    if @article.update_attributes(params[:article])
      redirect_to @article, :notice  => "Successfully updated article."
    else
      render :action => 'edit'
    end
  end
end

app/views/articles/index.html.erb
<%
set_meta_tags(
  description:'紀錄新聞錯誤，改善新聞品質。',
  og:{
    url:root_url,
    title:'新聞糾正',
    type:'website'
  }
)
%>
<%= form_tag articles_path do %>
  <%= url_field_tag :url, nil, placeholder:'貼上新聞 url 開始糾正' %>
  <%= submit_tag '糾正新聞', class:'btn btn-primary btn-large' %>
<% end %>
<p class="notice">目前能夠糾正的媒體網站為：<a href="http://appledaily.com.tw/" target="_blank">蘋果日報</a>、<a href="http://udn.com" target="_blank">聯合報</a>、<a href="http://www.chinatimes.com/" target="_blank">中國時報</a>、<a href="http://www.libertytimes.com.tw/" target="_blank">自由時報</a>、<a href="http://www.cna.com.tw/" target="_blank">中央社</a>、<a href="http://www.ettoday.net/" target="_blank">東森新聞</a>、<a href="http://www.tvbs.com.tw/" target="_blank">TVBS</a>、<a href="http://www.cts.com.tw/" target="_blank">華視</a>、<a href="http://www.nownews.com/" target="_blank">NowNews</a></p>

<p class="alert">如為當事人想要糾正，請先登入後，用右上方的Facebook認證，就可以開啟當事人認證功能</p>

<div class="row-fluid">
  <div class="span10">
    <% @articles.each do |article| %>
      <%= render_cell :article, :index_item, article %>
    <% end %>
  </div>
  <div class="span2">
    <%= render_cell :article, :company_list %>
  </div>
</div>

<%= paginate @articles %>

app/views/articles/reproduced.html.erb
<p>
  抱歉，這篇文章的出處是中央社，為了避免同一篇新聞多次評論的情況，請使用中央社的網址唷。
</p>

<p>
<%= search_term = "\"#{@article.title}\""
  link_to "Google 搜尋中央社新聞 #{@article.title}", "https://www.google.com.tw/#safe=off&q=#{CGI::escape(search_term)}+site:cna.com.tw", target:'_blank' %>
</p>

<p>
<%= form_tag articles_path do %>
  <%= url_field_tag :url %>
  <%= submit_tag '噓新聞' %>
<% end %>
</p>

app/views/articles/review.html.erb
<table class="table">
  <p><b>媒體：</b><%= @article.company_name %> <b>記者：</b><%= @article.reporter_name %></p>
  <h2><%= @article.title %></h2>
  <thead>
    <th class="content">內文</th>
    <th class="control"></th>
  </thead>
  <tbody>
<% @article.lines.each do |l| %>
  <tr>
    <td class="span6">
      <%= l.text %>
    </td>
    <td>
      <%= link_to '改正', new_review_path(line_id:l.id), class:'btn', :data => { :colorbox => true } %>
    </td>
    <% l.reviews.each do |r| %>
      <td>
        <span class="label"><%= r.tags.first.try(:name) %></span>
        <%= r.text_html %>
      </td>
    <% end %>
  </tr>
<% end %>
</tbody>
</table>

<h3>相關網頁</h3>
<p>與報導有相關但是非關事實對錯的連結，如反方報導或是深入閱讀等</p>
<table class='table'>
<% @article.links.each do |article| %>
  <tr>
    <td><%= article.url %></td>
    <td><%= article.description %></td>
  </tr>
<% end %>
</table>
<%= link_to '新增', new_article_link_path(@article), :data => { :colorbox => true }, class:'btn' %>

app/views/articles/show.html.erb
<style>
body, html{
  height:100%;
  margin:0;
  padding:0;
}
body{
  padding-top: 40px;
}
.source{
  height:100%; width:500px;
  float:left;
}
.source iframe{
  height: 99%; width: 100%; padding:0; margin:0; border:0;
}
.review{
  float:left;
  width:50%;
  padding:2em;
}
</style>
<%
set_meta_tags(
  title: [@article.company_name, @article.title],
  description: "關於「#{@article.title}」這篇報導，目前有#{@article.lines.where{reviews_count > 0}.count}個糾正。",
  og:{
    title: "新聞糾正：#{@article.company_name} #{@article.title}",
    type: 'article',
    url: article_url(@article)
  }
)
%>

<div class="source">
  <iframe src="<%= @article.url %>" sandbox="allow-forms"></iframe>
</div>

<div class="review">
  <p>
    <%= link_to "糾正本篇新聞", review_article_path(@article), class:'btn btn-warning' %>
  </p>
  <% @article.lines.where{reviews_count > 0}.each do |l| %>
    <div class="well">
      <blockquote><%= l.text %></blockquote>
      <% l.reviews.each do |r| %>
        <p>
          <span class="label"><%= r.tags.first.try(:name) %></span>
          <% if r.involved_personally? %>
            <%= link_to r.user, :data => { :colorbox => true } do %>
              <span class='label label-warning' style='text-decoration:underline'>我是當事人</span>
            <% end %>
          <% end %>
          <%= r.text_html %>
        </p>
        <% if can?(:destroy, r) %>
          <div class='control'>
            <%= link_to '刪除', review_path(r), method:'delete', class:'delete', confirm:'確定要刪除嗎？' %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <% if @article.links.present? %>
    <h3>相關連結</h3>
    <ul>
      <% @article.links.each do |link| %>
        <li><%= link_to link.description, link.url %></li>
      <% end %>
    </ul>
  <% end %>
<!--
  <p>
    <strong>Title:</strong>
    <%= @article.title %>
  </p>
  <p>
    <strong>Reporter Name:</strong>
    <%= @article.reporter_name %>
  </p>
  <p>
    <strong>Content:</strong>
    <% @article.lines.each do |l| %>
      <% if l.reviews.size > 0 %>
        <table>
          <tr>
            <td>
              <%= l.text %>
            </td>
          <% l.reviews.each do |r| %>
            <td>
            <%= r.text %>
            </td>
          <% end %>
        </tr>
      </table>
      <% end %>
    <% end %>
  </p>
  <p>
    <strong>Published At:</strong>
    <%= @article.published_at %>
  </p>
  <p>
    <strong>Url:</strong>
    <%= @article.url %>
  </p>
  <p>
    <strong>Company Name:</strong>
    <%= @article.company_name %>
  </p>
  -->
</div>