config/routes.rb
NewsSucks::Application.routes.draw do
  devise_for :users

  root :to => "articles#index"

  resources :articles, only:[:index, :show, :create, :update] do
    member do
      get :review
    end
    scope module: 'article' do
      resources :lines
    end
    resources :links
  end
  scope module: 'article' do
    resources :reviews
  end
  resources :suggestions, only:[:new, :create]

  resources :users, only:[:show]

  resources :identities, only:[:index, :create, :destroy]
  match '/auth/:provider/callback', to: 'identities#create'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= display_meta_tags %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>" data-controller="<%= controller_name %>" data-action="<%= action_name %>">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to '新聞糾正', root_url, class:"brand" %>
        <ul class="nav">
          <li>
            <%= link_to '《關於本站以及誠徵工作人員》', page_path('about') %>
          </li>
        </ul>
        <div class="nav-collapse collapse">
          <%= render :partial => "common/user_nav"%>
        </div>
      </div>
    </div>
  </div>

<%= yield %>

<hr />
<footer class="footer">
  <ul class="inline">
    <li>
      <%= link_to '關於本站以及誠徵工作人員', page_path('about') %>
    </li>
    <li>
      <%= link_to '聯絡我們 / 給我們意見 / 回報問題', new_suggestion_path %>
    </li>
  </ul>
</footer>

  <%= browserid_js_tag %>
  <%= javascript_include_tag "application" %>
</body>
</html>